### ISSUE TITLE
DxDataGrid Scrolling Virtual Mode

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular#81] opened 2016-08-16 20:23 UTC
Hi,

It doesn't seem to render with scroll.

Regards

**Comment by GoshaFighten** [comment] 2016-08-16 21:08
@Angelminster How does this work on you side? Do you have the grid occupying the whole page and the native scroll is displayed? If so, I think this relates to #45 . So, set the grid height explicitly. Check out the [https://github.com/GoshaFighten/Bug/tree/master/DXAngular2](https://github.com/GoshaFighten/Bug/tree/master/DXAngular2) project and let me know if it works for you.

**Comment by Angelminster** [comment] 2016-08-16 21:49
Hi @GoshaFighten!

1. I've setted the DxDataGrid max-heigth explicitly, if i don't set it the grid grows. 
2. Paging{ enabled: false} and scrolling{ mode:'virtual'}. Mode Virtual and paging are incompatible.

It shows the grid scroll and I can move it. Don't re-render when necessary. If i set mode standard it works without problems but it's slower.

I'll check your project and i'll tell u something.

Thanks!

**Comment by Angelminster** [comment] 2016-08-16 22:40
Your project works and I've found my problem.

I Had setted **max-heigth** and that does not work. We have to set **heigth**. I don't know why, is that a bug?

Thank You

**Comment by vconst** [comment] 2016-09-16 11:15
Hi!
 
I've researched the issue and have found that it is related to the incorrect dxDataGrid behavior and is reproduced without Angular2 integration. I've created a bugreport in the DevExpress Support Center so you can track our progress with it [here](https://www.devexpress.com/Support/Center/Question/Details/T427967).

**Comment by dxbykov** [comment] 2016-11-21 11:59
Since the issue is not related to angular 2 integration and is going to be processed outside this repo, I'm closing this issue.

**Closed by dxbykov** 2016-11-21 11:59 UTC
Labels: bug
