### ISSUE TITLE
dx-data-grid Angular2

### ISSUE THREAD

**Issue by lloydie3** [DevExpress/devextreme-angular#111] opened 2016-09-20 11:02 UTC
In Angular 1, I managed to implement DevExtreme alongside SignalR to continuously update a dx-data-grid with data which was displaying ticking data from the server. To get this to work, on the SignalR callback, I had to wrap the update of the values of the array in a $scope.$apply() to automatically push the results into the UI. 

I'm not sure on the whole digest or cycle methodology in Angular 2, but my understanding was that the equivalent would be zone.run(() => {} ); Wrapping my updates in this does not update the grid and therefore my grid can currently only be bound to data generated outside of SignalR.

Can you please let me know the relevant way to satisfy my requirement? I think that it's the last outstanding issue in migrating a quite complex system to use entirely DevExtreme controls with Angular 2 RC6.

thanks !

**Comment by Angelminster** [comment] 2016-09-20 12:35
Hi,

Angular 2 automatically applies changes to UI. No more $scope.$apply(). In your class superGrid you have a property "aGreatDataSource". In your html you bind that property to dxdatagrid datasource like this: <dx-data-grid             [dataSource]='aGreatDataSource' [...]

When you change "aGreatDataSource" it will be publish into the UI. 

I Suggest you to go throw Observables and Async pipe of Angular2. 
1. Create a service that return an Observable. 
2. Use the Async pipe inside de html: <dx-data-grid             [dataSource]='aGreatDataSource | Async' [...]
3. Your SingalIR will push the data -> change the observable -> Updates de UI asynchronously.

I have found a perfect example for you: https://blog.sstorie.com/integrating-angular-2-and-signalr-part-2-of-2/

Good Luck!

**Comment by lloydie3** [comment] 2016-09-20 22:53
That was my understanding of the mechanics of Angular2, but I simply cannot work out why the grid is not updating and therefore my last thought was to try and replicate the $scope.$apply through zone.run, since I had a similar problem before I used $scope.$apply in Angular 1.

I already have a typescript-ed SignalR service which was working in Angular 1 and was easily transferable to Angular 2 without the need for refactoring to use Observables. I can see that this is working when I replace the grid with a simple html table with ngFor for the rows.

Find below snippets of the code:

the non-working html:
```
<div>
</div>
        <dx-data-grid 
                        [dataSource]='trades | async' 
                        [columns]='[
                                    { dataField: "Asset", alignment: "center" },
                                    { dataField: "Bid", alignment: "center" },
                                    { dataField: "Ask", alignment: "center" },
                                    { dataField: "Time", alignment: "center", dataType: "date" }
                                   ]'>

        </dx-data-grid>

```
functional alternative html:
```

    <table>
        <thead>
            <tr>
                <th>Asset</th>
                <th>Bid</th>
                <th>Ask</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let trade of trades">
                <td>
                    {{trade.Asset}}
                </td>
                <td>
                    {{trade.Bid}}
                </td>
                <td>
                    {{trade.Ask}}
                </td>
                <td>
                    {{trade.Time}}
                </td>
            </tr>
        </tbody>
    </table>
```


component.ts

```

export class TradeViewModel {
    public trades: TradePrice[] = [];

    constructor(_signalRService: TradeHubProxy) {
        var tradeItems = this.trades;
        var self = this;

        _signalRService.registerCallback(function (asset, bid, ask, time) {
            var item = tradeItems.filter(t =>t.Name == asset.Name)[0];
            if (item == undefined) {
                    var mpvm = new TradePrice(asset, bid, ask, time);
                    tradeItems.push(mpvm);
              }
            else {
                    item.SetBidAsk(bid, ask, time);
             }
        });
    }

```


I've tried with and without the "| async". Using the " | async" makes the grid disappear completely without an exception. Without the " | async", I see the grid but it doesn't update.


FYI a further problem which I noticed: even with data generated outside SignalR, was that I could not use the DxDataGrid without a preceding `<div></div>` in the .html file. The example in GitHub works because there is a div element above the dx-data-grid. Without the div, if the array is empty, I see no headers at all, but once I add data into the array, I can see the table headers but the row entries never show up in the dx-data-grid. With the div above the data grid, I finally see the headers and the data as anticipated.

Sorry to not provide a plunker but the project is fairly large! Plus I think I am missing something very trivial here.

Thank you for your prompt response!

**Comment by Angelminster** [comment] 2016-09-21 01:27
Hi,

The Async pipe only works if the datasource is a Promise or an Observable. It makes the async subscription and updates the value automatically. I think you are pushing your values inside tradeItems, not in trades.

```
 _signalRService.registerCallback( (blabla) =>{
       this.trades.push(new TradePrice(blabla)); 
        });
```

In case you need to invoke angular 2 change detection you should inject it and use it:
[](https://angular.io/docs/ts/latest/api/core/index/ChangeDetectorRef-class.html)
ChangeDetectorRef.detectChanges() - similar to $scope.$digest()

**Comment by strpipe** [comment] 2016-09-21 14:31
I am also having problems with the grid not showing the data.

It creates one `<div class="dx-hidden"></div>` element for every entry of my array.

I also had to put a div element before the grid for it to show the rows.  Otherwise the grid only shows the  header.

**Comment by Angelminster** [comment] 2016-09-21 15:41
Add this css rule:
.dx-datagrid {
    display: block;
}
If you are not using Chrome this could be your issue #45  

I am too using Angular 2.0.0 in a very complex project and it's working. A simple example of a grid:
<dx-data-grid [ngStyle]="{'display': 'block'}"
              [columns]='columnsByFormat'
              [dataSource]='dataSourceContainer'>
</dx-data-grid>

In my class i have both properties columnsByFormat and dataSourceContainer. When i change the properties the grid updates and render the layout properly.

Hope it helps

**Comment by lloydie3** [comment] 2016-09-21 21:16
can you provide a more elaborate sample of your typescript?

I had to use the "tradeItems.push()" because the "this" has a different meaning inside the callback function and therefore "trades" is undefined - however, it relates to the same underlying referenced object. I believe this is standard java script behaviour for callback functions and I had to do the same in Angular 1, so I believe that the bound array is indeed updating correctly through this indirect approach. To provide another hypothesis - I tried an alternative method which was to just bind a button click to a method which would directly update the array with some simple values. However, it does work during the initialization of the component if I stick the push directly inside the constructor or ngInit().

I've tried using the observable with the async pipe and no luck. Neither did ChangeDetectorRef.detectChanges().

I would be very interested to see how you changed the properties.

thanks for your feedback

**Comment by Angelminster** [comment] 2016-09-21 21:30
To make 'this' the correct 'this' i use the arrow function. Look at my code (blabla) => {this.property}

You can use bind(this) too:

Http://stackoverflow.com/questions/37362178/this-scope-in-typescript-callback-function

Regards

**Comment by lloydie3** [comment] 2016-09-21 22:09
I've edited my code to use the arrow function which works perfectly in the sense that the array is  now properly updated from within the callback function whilst using the "this" function rather than my indirect reference. However, I still experience the same issue with the dx-data-grid. 

I did also try to update the grid using just a simple button which was bound to the component, and I received the same result of no grid update (with and without observables, with and without async pipes, with and without Detect Change), and I still get working behaviour only when I edit the array from the constructor or ngInit method

thanks!

**Comment by Angelminster** [comment] 2016-09-21 22:23
Can you post your complete component (with metadata @Component[...]) and your complete html?

I have it working like this:

[columns]='columnsByFormat'
[dataSource]='dataSourceContainer'

And in my component
ngAfterViewInit() {
        this.setColumnsByFormat();
}

  let formatColumns: Array<DevExpress.ui.dxDataGridColumn> = [];
        formatColumns = [
            { dataField: 'id', dataType: 'number', caption: 'Id', visible: false },
            { dataField: 'alarm__UserCreation__Name', dataType: 'string', caption: 'User'},
            { dataField: 'alarm__DateCreated', dataType: 'date', format: 'dd/MM/yyyy HH:mm', caption: ' Created', alignment: 'center', width: 110 },
        ];
        //Se asignan las columnas calculadas al valor que después se va a pasar a la rejilla. En teoría se deberían cambiar sin problemas en cualquier momento
        this.columnsByFormat = formatColumns;

**Comment by lloydie3** [comment] 2016-09-21 22:47
Ok so to roll back all the way to the code which was working in Angular1 with some basic additions for Angular 2. 

grid.html:
```

    <div>

    </div>

    <dx-data-grid
                    [dataSource]='trades'
                    [columns]='[
                                { dataField: "AssetName", alignment: "center" },
                                { dataField: "Bid", alignment: "center" },
                                { dataField: "Ask", alignment: "center" },
                                { dataField: "Time", alignment: "center", dataType: "date" }
                               ]'>

    </dx-data-grid>
```
component.ts

```

import {Component, Inject} from '@angular/core';
import {TradePrice} from './Models/TradePrice';

import { DevExtremeModule } from '../../../dist';
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { TradeHubProxy } from './../Services/SignalR/signalr.tradeHub.proxy.service';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'grid-view',
    templateUrl: '/Content/Templates/Angular2/grid.html'
})

@NgModule({
        imports: [BrowserModule, CommonModule],
    bootstrap: [TradeViewModel],
    declarations: [TradeViewModel, DevExtremeModule],
})


export class TradeViewModel {
    public trades: TradePrice[] = [];
    constructor( @Inject(TradeHubProxy) private _signalRService: TradeHubProxy) {
        super();
        
        this._signalRService.registerCallback((asset, bid, ask, time) => {
            var item = this.trades.filter(id => id.Name === asset.Name)[0];
            if (item == undefined) {
                var mpvm = new new TradePrice(asset, bid, ask, time);
                this.trades.push(mpvm);
            }
            else {
                item.SetMonitoredBidAskEntry(bid, ask, time);
            }});


    }
    
};
```

**Comment by Angelminster** [comment] 2016-09-21 22:48
DevextremeModule should be inside Imports, not declarations

**Comment by lloydie3** [comment] 2016-09-21 23:07
My bad - I updated the component but still not working. Tried as shown above, then with zone.run and detectChange

**Comment by Angelminster** [comment] 2016-09-21 23:22
Hi,

There is a known problem with the Devextreme components receiving collections. #53 . The Devextreme team are resolving this issue here today #112.

If you clone the array, it should work.

**Comment by lloydie3** [comment] 2016-09-21 23:34
Ok great - my updates are now feeding through, but I suppose I need to wait for the fix though because I need the utmost efficiency and cloning a grid of 1000's of items every second is not a solution I can use.

Do you mean they are releasing the fix today or just working on it?

Thanks for your help!

**Comment by Angelminster** [comment] 2016-09-21 23:49
Great! It's a pleasure to help. I've been figthing so much since the first angular 2 alphas release! 
You always can refresh the dxDataGrid manually if you have such a big array: 
   @ViewChild(DxDataGridComponent) dataGrid: DxDataGridComponent;
 (<DevExpress.ui.dxDataGrid>this.dataGrid.instance).refresh();

This solves your ploblem. My information is the same you have. That #112 ^_^

**Comment by Angelminster** [comment] 2016-09-22 09:47
If you refresh the grid manually you can push elements into the array and after that refresh the grid.

**Comment by lloydie3** [comment] 2016-09-22 10:10
Thanks for pushing for Angular 2! I'm finding my project much smaller and maintainable and there are just a few tweaks needed for dx, on the whole it seems to be quite functional in Angular2 already.

With regards to grid refreshing - I used this feature in Angular 1, and it results in a lock of the grid with an overlay displaying a "loading" image, making the existing items in the grid un-viewable and un-clickable. My users need to be able to see continuously ticking data and click any item, on an intra-second timescale and that functionality is the most important one for my project. I suspect this is by design therefore I would expect the same behaviour in Angular2. Therefore, the only alternative to really update the grid without regenerating it entirely is through the collection watchers which work in angular1 (despite the caveat of needing to use $scope.$apply()) and knockoutjs through the observables. I hope that the collection watcher will be fixed in Angular2 in a way which doesn't require the injection of $scope like objects or manually triggering update events - that will be a massive win in the migration.

**Comment by Angelminster** [comment] 2016-09-22 16:20
Hi,

Have you try loadPanel options on dxDataGrid?

loadPanel: {
                enabled: true,
                text: 'Formatting',
                showPane: true,
                showIndicator: true
            },

If you disable it, maybe you have your desire result.

**Comment by lloydie3** [comment] 2016-09-24 14:51
It works a lot better with refresh plus the load panel disabled. Thanks so much!

**Comment by lloydie3** [comment] 2016-09-25 14:07
Another few questions actually:

1) I noticed in another thread, you also had an issue with (onCellClick). I took only the dx.all file which they posted a few days ago, but I still have the same issue. Was that all you had to grab?

2) Have you noticed any issues with using jquery inside the grid? I had a .animate function on the cellElement which was being passed by the onCellChanged($event). It seems non-functional now, almost as if the function is blocked.

3) Not regarding dx-data-grid, but any other list based controls, eg dx-combo-box and dx-tree-view, if I press the dropdown triangle, it instantly expands then contracts the control. For the tree-view, I can drop it down by clicking the item rather than its drop down, however on the combo-box, a similar work around does not quite work, so I can never actually see the elements inside the combo-box. Is there something that I'm missing on those widgets?

thx

**Comment by Angelminster** [comment] 2016-09-25 21:53
Hello,

1. Yes. Only that file. Get the one inside of the zip posted by dokarus. [https://github.com/DevExpress/devextreme-angular2/files/476578/issue089.zip](url)

2. I Don't use JQuery. I had to import it because these components need it. I do the things the Angular way when it is possible. I haven't use that event by the moment but normally i can modify the elements without problems "e.rowElement.css('background', 'blue');". 

3. I'm using dx-select-box, dx-lookup, dx-tree-view without problems.

Regards!

**Comment by strpipe** [comment] 2016-09-26 11:25
I have still trouble getting the data grid to work.
The grid is showing the correct number of rows, however, the _inner Html_ of the columns is set on _&nbsp_, showing nothing.

I know for sure that the grid gets the data-source.

Can anybody help?

**Comment by strpipe** [comment] 2016-09-27 10:16
Okay, the column names had to match the datasource-property-names.

That was it.

Cheers!

**Comment by lloydie3** [comment] 2016-09-29 00:44
Regarding dx-data-grid again - any idea how the "dx-item-alias" maps in Angular2? Or if I can reference "this row's object" in a dxTemplate?  At the moment, when I use a cellTemplate, I have to use a dataField and the dxTemplate has access to only the property exposed in the dataField, whereas I would like all properties in each row.

EG before, I had a case where the template could contain:

{{item.Instrument}} - {{item.Bid}}

where "item" was the dx-item-alias for each grid row.

However, according to the sample, the usage is as follows:
dataField: "PropertyName", cellTemplate: "templateName"

<div *dxTemplate="let cellData = data of 'templateName'">
{{cellData.value}}
</div>
and cellData.value = PropertyName

Therefore with the example provided, I am limited to only referencing one property in my template when I need more than one of the properties.

thanks !

**Comment by Angelminster** [comment] 2016-10-03 14:37
Hi,

cellData is a complex object and you can access all of its properties. For instance:

{{cellData.data.Instrument}} - {{}cellData.data.Bid}
or {{cellData.values[2]}}

Regards

**Comment by dxbykov** [comment] 2016-11-30 15:51
It looks like the issue is resolved. @lloydie3 please refer to [this readme section](https://github.com/DevExpress/devextreme-angular#custom-templates).  For instance, you can declare a gird as follows:

```html
<dx-data-grid
    [columns]="[
        "CompanyName", 
        { 
            dataField: "Phone", 
            cellTemplate: "phoneCellTemplate" 
        }
    ]"
    [dataSource]="customers">
    <div *dxTemplate="let cellData of 'phoneCellTemplate'">
        <dx-button (onClick)="callNumber(cellData.value)" [text]="cellData.text"></dx-button>
    </div>
</dx-data-grid>
```
The `cellData` variable in this template declaration `*dxTemplate="let cellData of 'phoneCellTemplate'"` is an analog to `dx-item-alias` in the Angular 1 integration. I'm closing this issue. If you still have questions do not hesitate to reopen it.

**Closed by dxbykov** 2016-11-30 15:51 UTC
Labels: question
