### ISSUE TITLE
DxScheduler - An error occurs in the console on clicking an appointment

### ISSUE THREAD

**Issue by anna-zhernovkova** [DevExpress/devextreme-angular#191] opened 2016-11-01 13:24 UTC
Version 16.2.1-alpha.1

Error:
dx.template.js:64 Uncaught TypeError: renderData.container.empty is not a function

Reproduced in a local project with the following code:
```
<dx-scheduler [dataSource]="[]">
    <div *dxTemplate="let item of 'appointmentTooltipTemplate'">
         Hi
    </div>
</dx-scheduler>
```

To reproduce:
1. Create a new appointment
2. Click on an appointment

**Comment by dxbykov** [comment] 2016-11-21 12:17
I can't reproduce the issue with 16.2.1-alpha.3. So, I'm closing it.

**Closed by dxbykov** 2016-11-21 12:17 UTC
Labels: bug
