### ISSUE TITLE
ReferenceError: Node is not defined with angular universal build

### ISSUE THREAD

**Issue by sherry9872** [DevExpress/devextreme-angular#988] opened 2019-08-29 06:29 UTC
`<!--` *************************************************************************************************
To reduce the time it takes to process issues, search opened and closed tickets in our support center (https://www.devexpress.com/Support/Center/Question/List/1) before you submit a new issue. The tickets can contain resolutions, workarounds, or information about fixes.

You can also find information that can help you to resolve the issue in the following resources:

    - https://github.com/DevExpress/devextreme-angular/blob/master/README.md
    - https://js.devexpress.com/Documentation/Guide/Getting_Started/Widget_Basics_-_Angular/
******************************************************************************************************* -->

# Bug Report

**Package versions:**

    devexteme version: ^19.1.5
    devextreme-angular version:^19.1.5
"@angular/cli": "^8.2.1",
**Steps to reproduce:**

file -webpack.config.js
const path = require('path');
const webpack = require('webpack');

/**
 * This is a server config which should be merged on top of common config
 */
module.exports = {
  mode: 'development',
  externals: [/node_modules/],
  entry: {
    // This is our Express server for Dynamic universal
    server: './app-server/server.ts',
    // This is an example of Static prerendering (generative)
    // prerender: './app-server/prerender.ts'
  },
  resolve: { extensions: [".js", ".ts"] },
  output: {
    // Puts the output at the root of the dist folder
    path: path.join(__dirname, 'dist'),
    filename: '[name].js'
  },
  module: {
    rules: [
      { test: /\.ts$/, loader: 'ts-loader' },
      { 
        test: /\.css$/,
        use: [
          { loader: "style-loader" },
          { loader: "css-loader" }]
      },
      { 
        test: /\.(eot|svg|ttf|woff|woff2)$/, 
        use: "url-loader?name=[name].[ext]"
      }
    ]
  },
  plugins: [
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      /(.+)?angular(\\|\/)core(.+)?/,
      path.join(__dirname, 'src'), // location of your src
      {} // a map of your routes
    ),
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      /(.+)?express(\\|\/)(.+)?/,
      path.join(__dirname, 'src'),
      {}
    )
  ],
  target: 'node',
  node: {
    __dirname: false
  },
};

file - server.ts
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import { join } from 'path';
import setRoutes from './routes/routes';
const test = process.env['TEST'] === 'true';

const domino = require('domino');
const fs = require('fs');
const path = require('path');
const DIST_FOLDER = join(process.cwd(), 'dist/dist-client');
// const template = fs.readFileSync(path.join(__dirname, '.', '../dist/dist-client', 'index.html')).toString();
const template = fs.readFileSync(join(DIST_FOLDER, 'index.html')).toString();
const win = domino.createWindow(template);
const files = fs.readdirSync(`${process.cwd()}/dist/dist-server`);

global['window'] = win;
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true,
    };
  },
});
global['document'] = win.document;
global['CSS'] = null;
// global['XMLHttpRequest'] = require('xmlhttprequest').XMLHttpRequest;
global['Prism'] = null;

import { enableProdMode } from '@angular/core';
import * as express from 'express';
import * as compression from 'compression';
import * as cookieparser from 'cookie-parser';
const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');

const mainFiles = files.filter((file) => file.startsWith('main'));
const hash = mainFiles[0].split('.')[1];
const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require(`../dist/dist-server/main.${hash}`);
import { ngExpressEngine } from '@nguniversal/express-engine';
import { REQUEST, RESPONSE } from '@nguniversal/express-engine/tokens';
const PORT = process.env.PORT || 4000;
import { ROUTES } from './static.paths';
import { exit } from 'process';

enableProdMode();

const app = express();
app.use(compression());
app.use(cookieparser());

const redirectowww = false;
const redirectohttps = true;
const wwwredirecto = true;
app.use((req, res, next) => {
  // for domain/index.html
  if (req.url === '/index.html') {
    res.redirect(301, 'https://' + req.hostname);
  }

  // check if it is a secure (https) request
  // if not redirect to the equivalent https url
  if (
    redirectohttps &&
    req.headers['x-forwarded-proto'] !== 'https' &&
    req.hostname !== 'localhost'
  ) {
    // special for robots.txt
    if (req.url === '/robots.txt') {
      next();
      return;
    }
    res.redirect(301, 'https://' + req.hostname + req.url);
  }

  // www or not
  if (redirectowww && !req.hostname.startsWith('www.')) {
    res.redirect(301, 'https://www.' + req.hostname + req.url);
  }

  // www or not
  if (wwwredirecto && req.hostname.startsWith('www.')) {
    const host = req.hostname.slice(4, req.hostname.length);
    res.redirect(301, 'https://' + host + req.url);
  }

  // for test
  if (test && req.url === '/test/exit') {
    res.send('exit');
    exit(0);
    return;
  }

  next();
});

app.engine(
  'html',
  ngExpressEngine({
    bootstrap: AppServerModuleNgFactory,
    providers: [provideModuleMap(LAZY_MODULE_MAP)],
  }),
);

app.set('view engine', 'html');
app.set('views', 'src');
setRoutes(app);
app.get('*.*', express.static(path.join(__dirname, '.', 'dist-client')));
app.get(ROUTES, express.static(path.join(__dirname, '.', 'static')));

app.get('*', (req, res) => {
  global['navigator'] = req['headers']['user-agent'];
  const http =
    req.headers['x-forwarded-proto'] === undefined ? 'http' : req.headers['x-forwarded-proto'];

  const url = req.originalUrl;
  // tslint:disable-next-line:no-console
  console.time(`GET: ${url}`);
  res.render(
    '../dist/dist-client/index',
    {
      req: req,
      res: res,
      providers: [
        {
          provide: REQUEST,
          useValue: req,
        },
        {
          provide: RESPONSE,
          useValue: res,
        },
        {
          provide: 'ORIGIN_URL',
          useValue: `${http}://${req.headers.host}`,
        },
      ],
    },
    (err, html) => {
      if (!!err) {
        throw err;
      }

      // tslint:disable-next-line:no-console
      console.timeEnd(`GET: ${url}`);
      res.send(html);
    },
  );
});

app.listen(PORT, () => {
  console.log(`listening on http://localhost:${PORT}!`);
});

file angular.json
 "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",              
              "node_modules/devextreme/dist/css/dx.common.css",
              "node_modules/devextreme/dist/css/dx.light.compact.css",
              "src/styles.scss"
            ]

**Current behavior:**

It compiles but breaks at runtime.
webpack:///./node_modules/devextreme/core/dom_adapter.js?:52         return element && element.nodeType === Node.ELEMENT_NODE
**Expected behavior:**

**Screenshots:**

![image](https://user-images.githubusercontent.com/20853309/63916209-90b01300-ca55-11e9-906f-21f94c4a5491.png)

**Comment by hakimio** [comment] 2019-09-02 11:03
Can you reproduce with [Angular Universal example](https://github.com/DevExpress/devextreme-examples/tree/19_1/universal-angular)? If yes, create a github repository reproducing the issue.

**Comment by ovchinnikov** [comment] 2019-09-11 10:01
@sherry9872 Please provide me with a sample project that reproduces the issue.

**Comment by ovchinnikov** [comment] 2019-10-02 11:20
Duplicate of [T817844](https://www.devexpress.com/Support/Center/Question/Details/T817844/devetreme-angular-ssr-issue)

**Closed by ovchinnikov** 2019-10-02 11:20 UTC
