### ISSUE TITLE
TypeScript bindings for template cause error in VSCode

### ISSUE THREAD

**Issue by danielkalibri** [DevExpress/devextreme-angular#1031] opened 2020-01-28 17:05 UTC
**Current behavior:**
Visual Studio code 1.41 complains about dxTemplate elements

**Expected behavior:**
The template should resolve correctly.
Per this comment:
https://github.com/Apress/pro-angular-6/issues/6

I was able to change 
https://github.com/DevExpress/devextreme-angular/blob/master/src/core/template.ts#L36

I changed private templateRef: TemplateRef<any> to TemplateRef<{$implicit: any}> and the error went away. 

**Screenshots:**
Error in visual studio code

<img width="537" alt="Screen Shot 2020-01-28 at 11 59 58 AM" src="https://user-images.githubusercontent.com/60160957/73286969-7aee7780-41c6-11ea-9678-26ed5e2f55d6.png">

**Comment by ovchinnikov** [comment] 2020-01-29 08:26
Duplicate of [T856168](https://supportcenter.devexpress.com/ticket/details/t856168/the-the-template-context-of-dxtemplatedirective-does-not-define-an-implicit-value-error)

**Closed by ovchinnikov** 2020-01-29 08:26 UTC
