### ISSUE TITLE
Latest Angular version 9.0.0 next 10 causes all validators to fail

### ISSUE THREAD

**Issue by bobskigit** [DevExpress/devextreme-angular#1000] opened 2019-10-10 09:34 UTC
In the latest Angular 9 next 10, all Dx Validators fail with the following errors

**http://js.devexpress.com/error/19_1/E0120
    at makeError (error.js:52)
    at Object.Error (error.js:19)
    at inheritor._initAdapter (validator.js:67)
    at inheritor._init (validator.js:31)
    at inheritor._init (class.js:17)
    at inheritor.endUpdate (component.js:279)
    at inheritor.endUpdate (dom_component.js:280)
    at inheritor.endUpdate (class.js:17)
    at DxValidatorComponent.push../node_modules/devextreme-angular/core/component.js.DxComponent.ngAfterViewInit (component.js:182)
    at callProviderLifecycles (core.js:32586)**

To reproduce just add the following to any editor

<dx-validator>
        <dxi-validation-rule type="required" message="required"></dxi-validation-rule>
    </dx-validator>

**Comment by dxvladislavvolkov** [comment] 2019-11-18 11:07
Duplicate of [T831975](https://supportcenter.devexpress.com/internal/ticket/details/T831975)

**Closed by dxvladislavvolkov** 2019-11-18 11:07 UTC
