### ISSUE TITLE
dx-date-box localize into foreign language that is not into devextreme localization

### ISSUE THREAD

**Issue by bagratzakaryan** [DevExpress/devextreme-angular#914] opened 2018-12-10 08:06 UTC
Hello, I would like to localize [dx-date-box](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DateBox/Overview/Angular/SoftBlue/) in a foreign language that is not included into the [devextreme-localization](https://js.devexpress.com/Documentation/Guide/Common/Localization/) (the [Armenian),](https://en.wikipedia.org/wiki/Armenia) I'm working with [devextreme-intl](https://github.com/DevExpress/DevExtreme-Intl) , I added for the devextreme grid into `devextreme/localization/messages` but I can't go on with dx-date-box. Could you help me how to do it ?
This is the URL that I post same question into the [stackoverflow](https://stackoverflow.com/questions/53668467/localize-devextreme-dx-date-box-angular-2-in-custom-language)

And please when you install node-modules, after installation change the `module.exports = require("stream");` into `module.exports = require("readable-stream");`  the file url is `node_modules/jszip/lib/readable-stream-browser.js` 
[localizate-dx-date-box.zip](https://github.com/DevExpress/devextreme-angular/files/2662071/localizate-dx-date-box.zip) 

Thanks.

**Comment by ovchinnikov** [comment] 2018-12-18 06:30
Duplicate of T698989

**Closed by ovchinnikov** 2018-12-18 06:30 UTC

**Comment by bagratzakaryan** [comment] 2018-12-21 13:57
The question that was in Devexpress I've included.

**Comment by bagratzakaryan** [comment] 2018-12-22 12:45
this is my solution, please see.
**Devexpress.com**: [devexpress.com/Support/Center/Question](https://www.devexpress.com/Support/Center/Question/Details/T698989/how-to-localize-datebox-to-a-custom-language-in-angular)
**Stackoverflow**: [stackoverflow.com/questions/](https://stackoverflow.com/questions/53668467/localize-devextreme-dx-date-box-angular-2-in-custom-language/53895721#53895721)
