### ISSUE TITLE
Collection options don't work for nested components

### ISSUE THREAD

**Issue by dxvladislavvolkov** [DevExpress/devextreme-angular#226] opened 2016-11-16 15:28 UTC
[Here](http://plnkr.co/edit/3Dvjda5mKs6KA5zbhRg7?p=preview) is an example with the dxi-location option in the dx-responsive-box widget.

**Comment by dxbykov** [comment] 2016-11-30 14:41
This is a duplicate of #219.

**Closed by dxbykov** 2016-11-30 14:41 UTC
Labels: duplicate
