### ISSUE TITLE
IVY Support

### ISSUE THREAD

**Issue by agustins** [DevExpress/devextreme-angular#975] opened 2019-05-29 20:54 UTC
# Feature request

**Package versions you currently use:**

    devexteme version: 19.1.3
    devextreme-angular version: 19.1.3

**Description:**
Now with Angular 8 we can compile using IVY. But devextreme components fails with the following message:
`
node_modules/devextreme-angular/ui/data-grid.d.ts(1227,22): error TS-996002: Appears in the NgModule.imports of xxxxxx, but could not be resolved to an NgModule class`

It's in your plans to support ivy renderer? I dont see it in your roadmap.

**Comment by artem-kurchenko** [comment] 2019-05-31 14:53
Hi,
 
Yes, we'll keep 'Ivy' on our radar and have plans to support it. Please stay tuned.

**Comment by Franki1986** [comment] 2019-06-11 06:22
Hi, what is the status? Is there a version defined for this support?

**Comment by xxGizmoCodexx** [comment] 2019-06-24 12:27
Facing the same issue with our project's upgrade. Please keep us posted on info on plans for this feature

**Comment by jakehockey10** [comment] 2019-07-03 05:58
very interested in this topic

**Comment by jamra** [comment] 2019-07-04 18:52
What does "on our radar" mean? Does it mean that you know that your components don't work with Ivy or does it mean that you have plans to fix them?

**Comment by hakimio** [comment] 2019-07-04 19:29
@jamra They have plans to fix it. I would guess they will do that for the next major release coming around November.
Anyway, Ivy is still not considered stable, what's the rush?

**Comment by jamra** [comment] 2019-07-04 21:21
@hakimio I understand what "plans to support it" means. I just want to know if "on our radar" means sometime next year or in the next couple months. 

I need to make decisions based on these timelines and vague statements about time are concerning to me. If "plans to support it" and "on our radar" mean in a year or so, I will need to start looking into other components now as to prepare.

**Comment by NickMitrokhin** [comment] 2019-07-09 09:23
@jamra If all goes according to plan, we will support Ivy in 19.2, which will be released in November.

**Comment by jamra** [comment] 2019-07-11 17:55
@NickMitrokhin Thank you that's very nice to hear. Is it an issue with bundling or are there deeper issues that need to be changed in the core?

**Comment by NickMitrokhin** [comment] 2019-08-15 09:26
There are a lot of issues with IVY of different complexity. [Here](https://github.com/angular/angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22comp%3A+ivy%22+label%3A%22severity3%3A+broken%22) you will find several of them.

**Comment by Brandinga** [comment] 2019-08-24 18:58
Angular Team seems working on this ... see https://github.com/mgechev/ngcc-validation/issues/115

**Comment by artem-kurchenko** [comment] 2019-10-08 08:01
Hi All,

Ivy support is available starting with v19.2. 

You can test it using the devextreme and devextreme-angular  '19.2.2-beta'  packages. 
Note that long paths are not supported
`import { DxButtonModule } from 'devextreme-angular'; // OK `
`import { DxButtonModule } from 'devextreme-angular/ui/button';  // Won't work`

**Comment by bobskigit** [comment] 2019-10-14 15:35
I've just upgraded a large project and its now 40% smaller (8.9Mb to 4.7M) and appears quicker. Nice going gents.

**Comment by Franki1986** [comment] 2019-11-15 12:45
I have a problem with using ivy compilation. The problem is listed on Devexpress : 
[Ivy and dxvalidator](https://www.devexpress.com/Support/Center/Question/Details/T831975/angular-ivy-adapter-for-a-dxvalidator-component-cannot-be-configured)

**Comment by hakimio** [comment] 2019-11-15 12:49
@Franki1986 the fix might be in PR #1007.

**Comment by Franki1986** [comment] 2019-11-15 12:53
Thanks @hakimio . Any idea when a beta fix is ready? The fact that there are many validations in my application forces me to revert to disable ivy, the ugly thing is that every import has to be edited to use the specific file (long path)..

**Comment by hakimio** [comment] 2019-11-15 12:56
No idea. Maybe you should ask the person who submitted the PR.

**Comment by dxvladislavvolkov** [comment] 2019-11-15 13:25
Hi, @Franki1986 
We are going to publish a beta version that supports IVY after releasing 19.2.4. Please bear with us.

**Comment by Franki1986** [comment] 2019-11-15 13:26
Ok, I will revert my changes, thanks for giving info.

**Comment by LexDX** [comment] 2020-01-30 09:47
Starting with version 19.2.5 we support the IVY compiler. However, I'd like to note that the Angular team is still working on version 9 and they can make some changes in the final release. If you have any issues with newer Angular versions and our component operation, feel free to submit a ticket in our Support Center:
[https://www.devexpress.com/Support/Center/Question/Create](https://www.devexpress.com/Support/Center/Question/Create)

**Closed by LexDX** 2020-01-30 09:47 UTC
Labels: enhancement
