### ISSUE TITLE
Using Rollup with DevExtreme-Angular

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular#283] opened 2016-12-12 10:57 UTC
I have got webpack working with devextreme and my project. The javascript file size is around 7 Mb (unzipped).

From what I read treeshaking with the uglify plugin does not work. I tested it by adding a redundant method call and it was not removed.

http://blog.rangle.io/optimize-your-angular2-application-with-tree-shaking/

https://github.com/mishoo/UglifyJS2/issues/1261

Following the guide on the angular site for AOT, I tried using rollup, but I am not sure how to fix the problem that occurs.

https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

This gives errors with the dev extreme modules.

Error: 'DxAutocompleteModule' is not exported by node_modules\devextreme-angular\ui\autocomplete.js (imported by app\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

I tried using named exports but I am doing it incorrectly.

`import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify'

export default {
  entry: 'app/main.js',
  dest: 'dist/build.js', // output a single application bundle
  sourceMap: false,
  format: 'iife',
  plugins: [
      nodeResolve({jsnext: true, module: true}),
      commonjs({
        include: 'node_modules/rxjs/**',
        namedExports: {
    // left-hand side can be an absolute path, a path
    // relative to the current directory, or the name
    // of a module in node_modules
    'node_modules/devextreme-angular/ui/autocomplete.js': [ 'DxAutocompleteModule' ],
    'node_modules/devextreme-angular/ui/button.js': [ 'DxButtonModule' ],
    'node_modules/devextreme-angular/ui/calendar.js': [ 'DxCalendarModule' ],
    'node_modules/devextreme-angular/ui/chart.js': [ 'DxChartModule' ],
    'node_modules/devextreme-angular/ui/check-box.js': [ 'DxCheckBoxModule' ],
    'node_modules/devextreme-angular/ui/context-menu.js': [ 'DxContextMenuModule' ],
    'node_modules/devextreme-angular/ui/data-grid.js': [ 'DxDataGridModule' ],
    'node_modules/devextreme-angular/ui/date-box.js': [ 'DxDateBoxModule' ],
    'node_modules/devextreme-angular/ui/file-uploader.js': [ 'DxFileUploaderModule' ],
    'node_modules/devextreme-angular/ui/gallery.js': [ 'DxGalleryModule' ],
    'node_modules/devextreme-angular/ui/load-panel.js': [ 'DxLoadPanelModule' ],
    'node_modules/devextreme-angular/ui/list.js': [ 'DxListModule' ],
    'node_modules/devextreme-angular/ui/menu.js': [ 'DxMenuModule' ],
    'node_modules/devextreme-angular/ui/pie-chart': [ 'DxPieChartModule' ],
    'node_modules/devextreme-angular/ui/popup.js': [ 'DxPopupModule' ],
    'node_modules/devextreme-angular/ui/radio-group.js': [ 'DxRadioGroupModule' ],
    'node_modules/devextreme-angular/ui/select-box.js': [ 'DxSelectBoxModule' ],
   'node_modules/devextreme-angular/ui/tabs.js': [ 'DxTabsModule' ],
   'node_modules/devextreme-angular/ui/tag-box.js': [ 'DxTagBoxModule' ],
   'node_modules/devextreme-angular/ui/text-box.js': [ 'DxTextBoxModule' ],
   'node_modules/devextreme-angular/ui/text-area.js': [ 'DxTextAreaModule' ],
   'node_modules/devextreme-angular/ui/toast.js': [ 'DxToastModule' ],
   'node_modules/devextreme-angular/ui/toolbar.js': [ 'DxToolbarModule' ],
   'node_modules/devextreme-angular/ui/vector-map.js': [ 'DxVectorMapModule' ],
   'node_modules/devextreme-angular/core/dx.template.js': [ 'DxTemplateModule' ],
   'node_modules/devextreme-angular/ui/scroll-view.js': [ 'DxScrollViewModule' ],
   'node_modules/devextreme-angular/ui/tab-panel.js': [ 'DxTabPanelModule' ],
   'node_modules/devextreme-angular/ui/tooltip.js': [ 'DxTooltipModule' ]

  }
      }),
      uglify()
  ]
}`

Any guidance would be greatly appreciated.

**Comment by kvet** [comment] 2016-12-16 11:01
Hi!

AoT compilation has been fully tested in `angular-cli`. It works well.

But, there are tree-shaking issues with `webpack` without `angular-cli`. The main problem is that `devextreme` provides modules in commonjs format. This fact does not allow `webpack` to do it tree-shaking magic. As a workaround, I can suggest [loading `devextreme-angular` modules by long paths](https://github.com/DevExpress/devextreme-angular#bundlers-without-tree-shaking-support).

Bundling with `rollup` is broken. I have reproduced the same issue. I can suggest using `angular-cli` or `webpack` if it possible while we are working on this issue.

**Comment by rsantos-grv** [comment] 2016-12-19 12:26
Any time frame on resolving this issue?

**Comment by kvet** [comment] 2016-12-21 10:01
There are two problems with `rollup`
 
1. Currently, the `devextreme` package can't be used with the `rollup` bundler. We are working on this issue in the context of [T464712](https://isc.devexpress.com/Thread/WorkplaceDetails/T464712).
 
2. `devextreme-angular` provides modules in the commonjs format. Its entry point contains re-exports. This breaks bundling with the '.. not exported by ...' error. `rollup`, due to its implementation, can't process re-exports that we use in our package (despite the fact that it's usual practice).
 
Solution
 
For 16.2, we will support bundling with `rollup` only by using [long paths in imports](https://github.com/DevExpress/devextreme-angular#bundlers-without-tree-shaking-support). As I mentioned above, `devextreme` provides modules in the commonjs format. This means that `rollup` cannot tree-shake our sources without using long paths. If you use long paths, bundling works well without changes in `devextreme-angular`. We suppose that this is the only possible solution because the `devextreme` package doesn't support es2015 modules in the current release.
 
Also, I have prepared the `rollup` config to bundle the `angular` application that uses `devextreme-angular`:
```js
var rollup = require('rollup');
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var uglify = require('rollup-plugin-uglify');
var builtins = require('rollup-plugin-node-builtins');
var globals = require('rollup-plugin-node-globals');

rollup.rollup({
    ....
    plugins: [
        nodeResolve({ jsnext: true, main: true, browser: true, preferBuiltins: true }),
        commonjs(),
        builtins(),
        globals(),
        uglify()
    ]
}).then(...).catch(...);
```
 
We will update our documentation accordingly.

**Comment by kvet** [comment] 2017-01-23 14:03
Starting with the `16.2.4` release, bundling with `rollup` correctly works by using long paths.

Tree shaking support will be considered in the context of #353.

**Closed by kvet** 2017-01-23 14:03 UTC
Labels: bug
