### ISSUE TITLE
JSON parse error when i upgrade to angular 10

### ISSUE THREAD

**Issue by GuoHM** [DevExpress/devextreme-angular#1108] opened 2020-09-10 10:25 UTC
# Support Question

I have encounter a JSON parse error after try to load the report template when i upgrade from angular 8 to angular 10.
![image](https://user-images.githubusercontent.com/28671797/92717451-c68b1580-f392-11ea-8622-7bf70dbfeaa5.png)

However the same report template works fine when i use angular 8, but after i upgrade to angular 10 i have this error.

I am using devexpress 20.1.3

**Comment by hakimio** [comment] 2020-09-21 07:41
What is it trying to parse? Is it something downloaded? Do you get some network errors?

**Comment by GuoHM** [comment] 2020-09-22 01:52
> What is it trying to parse? Is it something downloaded? Do you get some network errors?

The issue has been solved by downgrade from 20.1.3 to 19.2.4

But i still quite confuse that when i use Angular 8 with devexpress 20.1.3 is fine, but once i upgrade my Angular to 10 both 20.1.3 and 20.1.7 is has this JSON parse issue, then i use Angular 10 with downgrade to 19.2.4 it works fine. The data load from backend is the same.

**Comment by Bykiev** [comment] 2020-10-05 16:51
@GuoHM, hi!
It's hard to detect the issue from your screenshot because it was run in prod, can you please try to run your app without minification and bundling?

**Comment by ovchinnikov** [comment] 2020-11-16 07:21
Duplicate of [t940587](https://supportcenter.devexpress.com/ticket/details/t940587/drawer-the-following-warning-appears-when-compiling-with-ivy-unable-to-fully-load-for)

**Closed by ovchinnikov** 2020-11-16 07:21 UTC
