### ISSUE TITLE
ERROR in ./node_modules/devextreme/client_exporter/excel_creator.js

### ISSUE THREAD

**Issue by tegarjgap** [DevExpress/devextreme-angular#779] opened 2018-05-06 09:12 UTC
devexteme version: "^17.2.7"
devextreme-angular version: "^17.2.7"

[x ] support inquiry 

Hi, I want to ask.. How to resolve my problem..
I has upgrade my project to angular 6 / angular-cli 6.. and I am getting error. I has try the solution in: https://github.com/angular/angular-cli/issues/9827#issuecomment-369647555.

but, i found new error with message like this:
![image](https://user-images.githubusercontent.com/17794532/39671718-2530e0fa-5148-11e8-9eb6-4733420730b4.png)

thank

**Comment by ovchinnikov** [comment] 2018-05-07 07:54
Please see the following comment: https://github.com/DevExpress/devextreme-angular/issues/776#issuecomment-386987213

Duplicate of #776

**Closed by ovchinnikov** 2018-05-07 07:54 UTC
