### ISSUE TITLE
Large Bundle Size

### ISSUE THREAD

**Issue by sheshit** [DevExpress/devextreme-angular#1038] opened 2020-02-17 09:31 UTC
I have imported these two components - 
import { DxChartModule } from 'devextreme-angular/ui/chart';
import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';

On my bundle size devextreme is 637 KB and devextreme-angular is 224 KB. Funny thing is initially I had short url's which imported whole package but even after changing the url to the long ones(like above), it still contributes the same to my bundle size. Is there any way to reduce it?

**Comment by jerousseau** [comment] 2020-02-17 10:30
Duplicate of https://github.com/DevExpress/devextreme-angular/issues/811

**Comment by hakimio** [comment] 2020-02-19 12:44
Are you also importing DX components like DxChartComponent from "devextreme-angular/ui"? There shouldn't be `import { DxFoo } from 'devextreme-angular'` anywhere in your app. 

What's the gzipped size?

**Comment by LexDX** [comment] 2020-03-27 07:15
Hi @sheshit,

@jerousseau is right. This is a duplicate of the #811 issue. In our RoadMap, we have plans to [split DevExtreme into modules](https://js.devexpress.com/Roadmap/#ArchitecturalEnhancements). Please stay tuned to our Blog posts and What's new articles.

**Closed by LexDX** 2020-03-27 07:15 UTC
Labels: duplicate
