### ISSUE TITLE
Warning: Entry point 'devextreme-angular/ui/tooltip' contains deep imports into > '/node_modules/devextreme/ui/tooltip', '/node_modules/devextreme/bundles/dx.all'

### ISSUE THREAD

**Issue by nigrosimone** [DevExpress/devextreme-angular#1068] opened 2020-04-30 07:09 UTC
# Bug Report

**Package versions:**

    devextreme: 19.2.7
    devextreme-angular: 19.2.7

**Steps to reproduce:**

Create a new Angular 9.1 project, install devextreme and run

```shell
ng serve
```

**Current behavior:**

the shell show some warnings like this:

> Warning: Entry point 'devextreme-angular/ui/tooltip' contains deep imports into
> '/node_modules/devextreme/ui/tooltip', '/node_modules/devextreme/bundles/dx.all'. This is probably not
>  a problem, but may cause the compilation of entry points to be out of order.

**Expected behavior:**

no warnings

**Comment by ovchinnikov** [comment] 2020-04-30 08:09
Duplicate of #1060

**Closed by ovchinnikov** 2020-04-30 08:09 UTC
